-- Trade intents — proposals generated by Strategy Employee Agents.
-- Each intent goes through the Risk Agent and may then sit in the
-- approval queue (approve_each mode) or auto-execute (autonomous mode).
-- See PLAN §7.2 for the lifecycle.

BEGIN;

CREATE TABLE trade_intents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Idempotency: gateway/order-router uses this as the request id for
    -- broker calls. Generated server-side.
    client_uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    agent_id   UUID NOT NULL REFERENCES agents(id)    ON DELETE CASCADE,

    -- Trade payload
    asset           TEXT NOT NULL,
    contract_type   TEXT NOT NULL,        -- MULTUP / MULTDOWN / ACCU / etc.
    direction       TEXT NOT NULL CHECK (direction IN ('up','down','flat')),
    stake_usd       NUMERIC(18,4) NOT NULL,
    multiplier      INTEGER,
    duration_secs   INTEGER NOT NULL,
    entry_price     NUMERIC(20,8) NOT NULL,
    stop_loss       NUMERIC(20,8),
    take_profit     NUMERIC(20,8),

    -- Why this intent exists
    source_model    TEXT NOT NULL,        -- e.g. 'ttm-granite-r2'
    source_asof_ts  TIMESTAMPTZ NOT NULL,
    confidence      NUMERIC(6,4) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    expected_payoff_ratio NUMERIC(8,4),
    expected_value_usd    NUMERIC(18,4),
    rationale       TEXT NOT NULL,

    -- Lifecycle
    status TEXT NOT NULL DEFAULT 'pending_risk'
        CHECK (status IN (
            'pending_risk',         -- waiting on Risk Agent
            'rejected_by_risk',
            'pending_approval',     -- user approval required
            'approved',             -- ready to submit
            'auto_approved',        -- autonomous mode
            'rejected_by_user',
            'expired',              -- approval window timed out
            'executed',             -- order placed on broker (stub for now)
            'failed_execution'
        )),
    risk_verdict        JSONB,      -- {ok, reason, checks: [...], applied_caps}
    user_decision_by    UUID REFERENCES accounts(id) ON DELETE SET NULL,
    user_decision_at    TIMESTAMPTZ,
    user_decision_reason TEXT,

    -- Approval window expiry — 30s default in approve_each
    expires_at TIMESTAMPTZ,

    -- Execution (stubbed in Phase 1 — populated in Phase 7 when we wire
    -- the actual Deriv buy/sell flow).
    executed_at        TIMESTAMPTZ,
    broker_contract_id TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_intents_company_status_ts ON trade_intents (company_id, status, created_at DESC);
CREATE INDEX idx_intents_agent_ts ON trade_intents (agent_id, created_at DESC);
CREATE INDEX idx_intents_pending_expiry ON trade_intents (expires_at)
    WHERE status IN ('pending_approval','pending_risk');

CREATE TRIGGER tr_intents_updated_at BEFORE UPDATE ON trade_intents
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
