"""Trade postmortems: per-trade analysis of the full decision → close path.

Read-only. Postmortems are generated by the execution consumer when a trade
settles (app.postmortem.generate); these routes just surface them.
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Annotated, Any, Literal
from uuid import UUID

import asyncpg
from fastapi import APIRouter, HTTPException, Query, status
from pydantic import BaseModel

from app.auth import CurrentAccount
from app.db import acquire

router = APIRouter(prefix="/companies/{company_id}", tags=["postmortems"])


# ───────────────────────── schemas ──────────────────────────


class Postmortem(BaseModel):
    id: UUID
    intent_id: UUID
    company_id: UUID
    agent_id: UUID | None
    agent_name: str | None
    asset: str | None
    contract_type: str | None
    direction: str | None
    outcome: str
    pnl_usd: float
    entry_trace: dict
    exit_trace: dict
    employee_rating: dict
    narrative: str
    generated_at: datetime


class PostmortemList(BaseModel):
    postmortems: list[Postmortem]
    total: int
    limit: int
    offset: int


# ───────────────────────── helpers ──────────────────────────


async def _ensure_member(conn: asyncpg.Connection, company_id: UUID, account_id: UUID) -> str:
    role = await conn.fetchval(
        "SELECT role FROM company_members WHERE company_id=$1 AND account_id=$2",
        company_id, account_id,
    )
    if role is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "company not found")
    return role


def _j(v):
    return json.loads(v) if isinstance(v, str) else (v or {})


def _row(r: asyncpg.Record) -> Postmortem:
    return Postmortem(
        id=r["id"],
        intent_id=r["intent_id"],
        company_id=r["company_id"],
        agent_id=r["agent_id"],
        agent_name=r["agent_name"],
        asset=r["asset"],
        contract_type=r["contract_type"],
        direction=r["direction"],
        outcome=r["outcome"],
        pnl_usd=float(r["pnl_usd"]),
        entry_trace=_j(r["entry_trace"]),
        exit_trace=_j(r["exit_trace"]),
        employee_rating=_j(r["employee_rating"]),
        narrative=r["narrative"],
        generated_at=r["generated_at"],
    )


_SELECT = """
    SELECT p.*, a.name AS agent_name,
           i.asset, i.contract_type, i.direction
    FROM trade_postmortems p
    LEFT JOIN agents a ON a.id = p.agent_id
    LEFT JOIN trade_intents i ON i.id = p.intent_id
"""


# ───────────────────────── routes ──────────────────────────


@router.get("/postmortems", response_model=PostmortemList)
async def list_postmortems(
    company_id: UUID,
    account_id: CurrentAccount,
    agent_id: Annotated[UUID | None, Query()] = None,
    asset: Annotated[str | None, Query(min_length=1, max_length=32)] = None,
    outcome: Annotated[Literal["win", "loss", "neutral"] | None, Query()] = None,
    q: Annotated[str | None, Query(min_length=1, max_length=200, description="text search across narrative")] = None,
    limit: Annotated[int, Query(ge=1, le=200)] = 25,
    offset: Annotated[int, Query(ge=0)] = 0,
):
    # Build dynamic WHERE clauses. asyncpg uses positional $N — keep a
    # parallel args list so the placeholders stay in step.
    clauses: list[str] = ["p.company_id = $1"]
    args: list[Any] = [company_id]
    if agent_id is not None:
        args.append(agent_id)
        clauses.append(f"p.agent_id = ${len(args)}")
    if asset is not None:
        args.append(asset)
        clauses.append(f"i.asset = ${len(args)}")
    if outcome is not None:
        args.append(outcome)
        clauses.append(f"p.outcome = ${len(args)}")
    if q is not None:
        args.append(f"%{q}%")
        clauses.append(f"p.narrative ILIKE ${len(args)}")
    where = " AND ".join(clauses)

    page_sql = _SELECT + f"""
        WHERE {where}
        ORDER BY p.generated_at DESC
        LIMIT ${len(args) + 1} OFFSET ${len(args) + 2}
    """
    count_sql = f"""
        SELECT count(*) AS n
        FROM trade_postmortems p
        LEFT JOIN trade_intents i ON i.id = p.intent_id
        WHERE {where}
    """

    async with acquire() as conn:
        await _ensure_member(conn, company_id, account_id)
        total = await conn.fetchval(count_sql, *args)
        rows = await conn.fetch(page_sql, *args, limit, offset)

    return PostmortemList(
        postmortems=[_row(r) for r in rows],
        total=int(total or 0),
        limit=limit,
        offset=offset,
    )


@router.get("/postmortems/facets")
async def list_postmortem_facets(
    company_id: UUID, account_id: CurrentAccount,
):
    """Distinct values the UI uses to populate filter dropdowns. Cheap;
    folds into one query."""
    async with acquire() as conn:
        await _ensure_member(conn, company_id, account_id)
        rows = await conn.fetch(
            """
            SELECT i.asset AS asset, a.id AS agent_id, a.name AS agent_name
            FROM trade_postmortems p
            JOIN trade_intents i ON i.id = p.intent_id
            LEFT JOIN agents a ON a.id = p.agent_id
            WHERE p.company_id = $1
            """,
            company_id,
        )
    assets = sorted({r["asset"] for r in rows if r["asset"]})
    seen: dict[str, str] = {}
    for r in rows:
        if r["agent_id"] and r["agent_name"]:
            seen[str(r["agent_id"])] = r["agent_name"]
    agents = [{"id": k, "name": v} for k, v in sorted(seen.items(), key=lambda kv: kv[1].lower())]
    return {"assets": assets, "agents": agents}


@router.get("/intents/{intent_id}/postmortem", response_model=Postmortem)
async def get_postmortem(
    company_id: UUID, intent_id: UUID, account_id: CurrentAccount,
):
    async with acquire() as conn:
        await _ensure_member(conn, company_id, account_id)
        row = await conn.fetchrow(
            _SELECT + """
            WHERE p.company_id = $1 AND p.intent_id = $2
            """,
            company_id, intent_id,
        )
    if row is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "no postmortem for this intent")
    return _row(row)
