"""Trade postmortems: per-trade analysis of the full decision → close path.

Read-only. Postmortems are generated by the execution consumer when a trade
settles (app.postmortem.generate); these routes just surface them.
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Annotated
from uuid import UUID

import asyncpg
from fastapi import APIRouter, HTTPException, Query, status
from pydantic import BaseModel

from app.auth import CurrentAccount
from app.db import acquire

router = APIRouter(prefix="/companies/{company_id}", tags=["postmortems"])


# ───────────────────────── schemas ──────────────────────────


class Postmortem(BaseModel):
    id: UUID
    intent_id: UUID
    company_id: UUID
    agent_id: UUID | None
    agent_name: str | None
    asset: str | None
    contract_type: str | None
    direction: str | None
    outcome: str
    pnl_usd: float
    entry_trace: dict
    exit_trace: dict
    employee_rating: dict
    narrative: str
    generated_at: datetime


class PostmortemList(BaseModel):
    postmortems: list[Postmortem]


# ───────────────────────── helpers ──────────────────────────


async def _ensure_member(conn: asyncpg.Connection, company_id: UUID, account_id: UUID) -> str:
    role = await conn.fetchval(
        "SELECT role FROM company_members WHERE company_id=$1 AND account_id=$2",
        company_id, account_id,
    )
    if role is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "company not found")
    return role


def _j(v):
    return json.loads(v) if isinstance(v, str) else (v or {})


def _row(r: asyncpg.Record) -> Postmortem:
    return Postmortem(
        id=r["id"],
        intent_id=r["intent_id"],
        company_id=r["company_id"],
        agent_id=r["agent_id"],
        agent_name=r["agent_name"],
        asset=r["asset"],
        contract_type=r["contract_type"],
        direction=r["direction"],
        outcome=r["outcome"],
        pnl_usd=float(r["pnl_usd"]),
        entry_trace=_j(r["entry_trace"]),
        exit_trace=_j(r["exit_trace"]),
        employee_rating=_j(r["employee_rating"]),
        narrative=r["narrative"],
        generated_at=r["generated_at"],
    )


_SELECT = """
    SELECT p.*, a.name AS agent_name,
           i.asset, i.contract_type, i.direction
    FROM trade_postmortems p
    LEFT JOIN agents a ON a.id = p.agent_id
    LEFT JOIN trade_intents i ON i.id = p.intent_id
"""


# ───────────────────────── routes ──────────────────────────


@router.get("/postmortems", response_model=PostmortemList)
async def list_postmortems(
    company_id: UUID,
    account_id: CurrentAccount,
    agent_id: Annotated[UUID | None, Query()] = None,
    limit: Annotated[int, Query(ge=1, le=200)] = 50,
):
    async with acquire() as conn:
        await _ensure_member(conn, company_id, account_id)
        if agent_id is not None:
            rows = await conn.fetch(
                _SELECT + """
                WHERE p.company_id = $1 AND p.agent_id = $2
                ORDER BY p.generated_at DESC
                LIMIT $3
                """,
                company_id, agent_id, limit,
            )
        else:
            rows = await conn.fetch(
                _SELECT + """
                WHERE p.company_id = $1
                ORDER BY p.generated_at DESC
                LIMIT $2
                """,
                company_id, limit,
            )
    return PostmortemList(postmortems=[_row(r) for r in rows])


@router.get("/intents/{intent_id}/postmortem", response_model=Postmortem)
async def get_postmortem(
    company_id: UUID, intent_id: UUID, account_id: CurrentAccount,
):
    async with acquire() as conn:
        await _ensure_member(conn, company_id, account_id)
        row = await conn.fetchrow(
            _SELECT + """
            WHERE p.company_id = $1 AND p.intent_id = $2
            """,
            company_id, intent_id,
        )
    if row is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "no postmortem for this intent")
    return _row(row)
